version: 2.1

orbs:
  android: circleci/android@0.2.3
jobs:
  build:
    docker:
      - image: circleci/android:api-29-ndk
    environment:
      JVM_OPTS: -Xmx2048m
      GRADLE_OPTS: -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    steps:
      - checkout
      - android/restore-build-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - android/save-build-cache
      - run:
          name: Lint Test Package
          command: ./gradlew lintConscriptExternRelease testConscriptExternRelease assembleConscriptExternDebugAndroidTest :myExpenses:packageConscriptExternReleaseUniversalApk --no-daemon
      - store_artifacts:
          path: myExpenses/build/reports
          destination: reports
      - store_test_results:
          path: myExpenses/build/test-results


